services:
  db:
    image: postgres:16.1
    container_name: communication_postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backups:/backups

  adminer:
    image: adminer:latest
    container_name: communication_adminer
    restart: unless-stopped
    ports:
      - "8000:8080"
    depends_on:
      - db

# Define named volumes
volumes:
  postgres_data:
    driver: local

networks:
  communication_network:
    driver: bridge
